# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MeshiMatching' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeshiMatching
  pod 'FSCalendar'
  pod 'CalculateCalendarLogic'
  pod 'ACEDrawingView'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Alamofire-SwiftyJSON'
  
  target 'MeshiMatchingTests' do
    inherit! :search_paths
    
    # Pods for testing
    
  end
end
